#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

export PATH=/usr/local/bin:$PATH
export PATH=$HOME/flutter/bin:$PATH

FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.dart" | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

echo "$FILES" | xargs -I {} dart format {} -l 150
echo "$FILES" | xargs git add

exit 0